services:
  focus_db:
    container_name: focus_db
    image: postgres:17.5
    env_file: ".env"
    ports:
      - "5432:5432"
    volumes:
      - focus_pgdata:/var/lib/postgres/focus

  focus_app:
    container_name: focus_app
    build: .
    env_file: ".docker.env"
    ports:
      - "8000:8000"

volumes:
  focus_pgdata: